server:
  port: ${port:8080}
  shutdown: graceful #开启优雅停机
spring:
  profiles:
    active: ${profile:dev}
  application:
    name: SpringBoot3Application
  security:
    user:
      name: admin
      password: 123456
management:
  server:
    port: 36666
  endpoints:
    web:
      base-path: /_manage
      discovery:
        enabled: true
      exposure:
        include: "*"
        exclude: "heapdump"
    jmx:
      exposure:
        include: "*"
        exclude: "heapdump"
    enabled-by-default: true
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    redis:
      enabled: true
    rabbit:
      enabled: true
    diskspace:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          up: 200
          down: 503
          fatal: 503
          out-of-service: 503
    refresh:
      enabled: true
    heapdump:
      enabled: false
    prometheus:
      enabled: true
    shutdown:
      enabled: false
    mappings:
      enabled: true
  metrics:
    use-global-registry: true
